name: Resources
on: 
  workflow_dispatch:
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1

            - name: Fetch resources
              run: ./public/atul.txt
              
            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: ./public/atul.txt
                  commit-msg: Update resources
                  github-token: ${{ secrets.GITHUB_TOKEN }}
